-- =========================================
-- SCHEMA
-- =========================================
CREATE SCHEMA IF NOT EXISTS public;

-- =========================================
-- TABELA: aluno
-- =========================================
CREATE TABLE IF NOT EXISTS public.aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(150) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(150),
    data_nascimento DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- =========================================
-- TABELA: periodo_letivo
-- =========================================
CREATE TABLE IF NOT EXISTS public.periodo_letivo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_periodo_letivo_datas 
        CHECK (data_fim >= data_inicio)
);

-- =========================================
-- TABELA: turma
-- =========================================
CREATE TABLE IF NOT EXISTS public.turma (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    capacidade INTEGER NOT NULL CHECK (capacidade > 0),
    periodo_letivo_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uk_turma_codigo_periodo 
        UNIQUE (codigo, periodo_letivo_id),

    CONSTRAINT fk_turma_periodo_letivo 
        FOREIGN KEY (periodo_letivo_id) 
        REFERENCES public.periodo_letivo(id)
);

-- =========================================
-- TABELA: matricula
-- =========================================
CREATE TABLE IF NOT EXISTS public.matricula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL,
    turma_id BIGINT NOT NULL,
    periodo_letivo_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVA',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT ck_matricula_status 
        CHECK (status IN ('ATIVA', 'CANCELADA', 'TRANCADA')),

    CONSTRAINT fk_matricula_aluno 
        FOREIGN KEY (aluno_id) 
        REFERENCES public.aluno(id),

    CONSTRAINT fk_matricula_turma 
        FOREIGN KEY (turma_id) 
        REFERENCES public.turma(id),

    CONSTRAINT fk_matricula_periodo_letivo 
        FOREIGN KEY (periodo_letivo_id) 
        REFERENCES public.periodo_letivo(id)
);

-- =========================================
-- TABELA: flyway_audit_marker (opcional)
-- =========================================
CREATE TABLE IF NOT EXISTS public.flyway_audit_marker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- =========================================
-- ÍNDICES
-- =========================================
CREATE INDEX IF NOT EXISTS idx_matricula_aluno 
    ON public.matricula(aluno_id);

CREATE INDEX IF NOT EXISTS idx_matricula_turma 
    ON public.matricula(turma_id);

CREATE INDEX IF NOT EXISTS idx_turma_periodo 
    ON public.turma(periodo_letivo_id);